### PR TITLE
Fix smooth speed in windows

### PR DESCRIPTION
**Pull request by Susensio**
#1 Maybe this would fix it

### CODE REVIEW

**Comment by Dedas** [comment]
I'm sorry but that is just part of the setting to turn on and off CSS smooth scrolling and not part of how Chrome for Linux handles the "smooth" effect when scrolling. I added a toggle for CSS smooth scrolling due to it interfering with the plugins way of handling scrolling in Chrome for Linux. You can turn it off and on yourself and try it out on pages where CSS smooth scrolling is enabled.

I will continue investigating if it is possible to replicate the effect you are looking for within the plugin.

**Comment by Susensio** [comment]
Maybe the extension could be disabled altogether in windows? The default windows scrolling behaviour is perfect, and the default linux is unusable. Your extension improves linux behaviour and makes it almost perfect. If only I could combine the default windows + extension linux. Right now I find myself enabling and disabling the extension.

**Comment by Dedas** [comment]
I can definitely release a version where the default Windows setting is that the plugin is disabled (with the option to enable).

**Comment by Dedas** [comment]
The new version 1.6.1 defaults to the extension being disabled in Windows.

**Pull request closed without merging**
